### ISSUE TITLE
Publish to Maven Central or Bintray

### ISSUE THREAD

**Issue by Shusshu** [tumblr/Backboard#1]
Any plan to publish it?

Thanks for this lib, looks great.

**Comment by brianmichel** [comment]
Hey @Shusshu we will be getting around to this real soon. @ericleong can you take care of this?

**Comment by ericleong** [comment]
Yup, working on it!

**Comment by KevinTCoughlin** [comment]
:+1:

**Comment by ericleong** [comment]
[Published to bintray](https://bintray.com/ericleong/maven/Backboard/view), you can add it to your project like this:

``` java
dependencies {
    compile 'com.facebook.rebound:rebound:0.3.8'
    compile 'com.tumblr:backboard:0.1.0'
}
```

Make sure you have `jcenter()` in your list of repositories!
