### ISSUE TITLE
How can i use this for “overridePendingTransition” between Activity？

### ISSUE THREAD

**Issue by NicodeLee** [tumblr/Backboard#12]
Support for it？

**Comment by ericleong** [comment]
I'm not exactly sure what you're hoping to do, but [Dragger](https://github.com/ppamorim/Dragger) should be able to handle simple cases. A custom [DraggerView](https://github.com/ppamorim/Dragger/blob/master/dragger/src/main/java/com/github/ppamorim/dragger/DraggerView.java) could be used with this library for more complex gestures.
