### ISSUE TITLE
RecyclerView usage

### ISSUE THREAD

**Issue by FunnyDevs** [tumblr/Backboard#13]
Is possibile to use a nested scrolling view (recyclerview,scrollview) with this library??

**Comment by ericleong** [comment]
It depends on the effect you're going for, but in general, once the view is touched, call [ViewParent#requestDisallowInterceptTouchEvent()](http://developer.android.com/reference/android/view/ViewParent.html#requestDisallowInterceptTouchEvent%28boolean%29) on the parent view. If using an `Actor`, use [Actor.Builder#requestDisallowTouchEvent()](http://tumblr.github.io/Backboard/javadoc/com/tumblr/backboard/Actor.Builder.html#requestDisallowTouchEvent%28%29) for similar behavior.
