### ISSUE TITLE
Update Gradle dependency

### ISSUE THREAD

**Issue by veyndan** [tumblr/Backboard#14]
Is it possible to update the Backboard Gradle dependency from `0.1.0`? Some of the examples in `backboard-example` are not possible to migrate over to my own codebase, for example in `PressFragment` there is an `addMotion` method where an `EventImitator` is passed in but the current version in Bintray does not have that.

**Comment by steelrooter** [comment]
Basically make a new release

**Comment by ericleong** [comment]
Sorry for the _extreme_ delay: [v0.1.1](https://github.com/tumblr/Backboard/releases/tag/v0.1.1)

**Comment by veyndan** [comment]
Awesome!
