### ISSUE TITLE
Add some demo link in readme.md

### ISSUE THREAD

**Issue by jitendra3109** [tumblr/Backboard#19]
Can you please add some demo part of the link or GIF image for animation?
It would be great.

**Comment by ericleong** [comment]
Are you suggesting a link to [the demo app](https://github.com/tumblr/Backboard/releases/download/v0.1.2/backboard-example.apk) and a link to [these gifs](https://plus.google.com/103746199749981693463/posts/YwoUrJN4ez5)? My only issue with the gifs is that they are large.

**Comment by jitendra3109** [comment]
Yes! I was suggesting the preview of App any of way either GIF or Demo.
I saw the GIF from G+ and it is nice.
At least added some screenshots.
